# -*- coding: utf-8 -*-
"""Tut6_pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDnd30sutT1cxOkHKIjvbcx84fxFnfZD
"""
#Tahniat Khayyam 577608

img_path=r"dog.jpg"

import torch
from torchvision import models, transforms
from PIL import Image
import requests

# 1. Define the Preprocessing Pipeline
# PyTorch models require specific normalization for pre-trained ImageNet weights
preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

def predict_image(img_path, model_name):
    # Load and preprocess image
    img = Image.open(img_path).convert('RGB')
    img_t = preprocess(img)
    batch_t = torch.unsqueeze(img_t, 0)

    # Load the requested model
    if model_name == 'vgg16':
        model = models.vgg16(pretrained=True)
    elif model_name == 'resnet50':
        model = models.resnet50(pretrained=True)
    elif model_name == 'alexnet':
        model = models.alexnet(pretrained=True)
    elif model_name == 'resnet101':
        model = models.resnet101(pretrained=True)
    elif model_name == 'mobilenet':
        model = models.mobilenet_v2(pretrained=True)

    model.eval() # Set to evaluation mode

    # Perform inference
    with torch.no_grad():
        out = model(batch_t)

    # Get top 5 predictions
    prob = torch.nn.functional.softmax(out, dim=1)[0]
    top5_prob, top5_catid = torch.topk(prob, 5)

    # Load ImageNet labels
    LABELS_URL = "https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt"
    labels = requests.get(LABELS_URL).text.splitlines()

    print(f"\nTop 5 predictions from {model_name}:")
    for i in range(top5_prob.size(0)):
        print(f"{i+1}. {labels[top5_catid[i]]} ({top5_prob[i].item()*100:.2f}% probability)")

predict_image(img_path, 'vgg16')

predict_image(img_path, 'resnet50')

predict_image(img_path, 'alexnet')

predict_image(img_path, 'resnet101')

predict_image(img_path, 'mobilenet')

"""Transfer Learning with Stanford Dogs dataset

With ResNet101, Resnet50, alexnet, mobilnetv2, and vgg16
"""

import torch
import torch.nn as nn
from torchvision import models, transforms, datasets
from PIL import Image
import matplotlib.pyplot as plt
import random
import requests

# 1. Setup Preprocessing (Standard for ImageNet-based models)
preprocess = transforms.Compose([

    transforms.CenterCrop(224),
    transforms.ToTensor(),

])

# 2. Download the Oxford-IIIT Pet Dataset
# This handles the download link and extraction automatically
pet_dataset = datasets.OxfordIIITPet(
    root='./data',
    split='trainval',
    download=True,
    transform=preprocess
)

# 3. Prediction Function with Transfer Learning
def predict_image(img_tensor, model_name):
    # Load the requested model with pre-trained weights
    if model_name == 'vgg16':
        model = models.vgg16(weights='IMAGENET1K_V1')
    elif model_name == 'resnet50':
        model = models.resnet50(weights='IMAGENET1K_V1')
    elif model_name == 'alexnet':
        model = models.alexnet(weights='IMAGENET1K_V1')
    elif model_name == 'resnet101':
        model = models.resnet101(weights='IMAGENET1K_V1')
    elif model_name == 'mobilenet':
        model = models.mobilenet_v2(weights='IMAGENET1K_V1')

    model.eval() # Set to evaluation mode

    # Prepare batch (add dimension for batch size)
    input_batch = img_tensor.unsqueeze(0)

    # Perform inference
    with torch.no_grad():
        output = model(input_batch)

    # Get top 5 probabilities
    probabilities = torch.nn.functional.softmax(output[0], dim=0)
    top5_prob, top5_catid = torch.topk(probabilities, 5)

    # Load ImageNet labels for human-readable output
    labels_url = "https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt"
    labels = requests.get(labels_url).text.splitlines()

    print(f"\n--- Top 5 Predictions ({model_name.upper()}) ---")
    for i in range(top5_prob.size(0)):
        print(f"{i+1}. {labels[top5_catid[i]]} ({top5_prob[i].item()*100:.2f}%)")

# 4. Execution: Pick a random image and predict
# Select a random index from the dataset
random_idx = random.randint(0, len(pet_dataset) - 1)
img_tensor, actual_label_idx = pet_dataset[random_idx]

# Show the image (Note: permute is needed for Matplotlib)
plt.imshow(img_tensor.permute(1, 2, 0))
plt.title(f"Random Image from Dataset (Index: {random_idx})")
plt.axis('off')
plt.show()

# Run predictions across your models
predict_image(img_tensor, 'resnet101')
predict_image(img_tensor, 'alexnet')
predict_image(img_tensor, 'mobilenet')
predict_image(img_tensor,'resnet50')
predict_image(img_tensor,'vgg16')

#printing actual label
label=pet_dataset.classes[actual_label_idx]
print(f"\nActual Label: {label}")