# -*- coding: utf-8 -*-
"""Tut6_keras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UKWpDjo5DE5ZaEBljWrmFRJ3tiurGfJI
"""


#Tahniat Khayyam 577608
#DeepLearning Course Spring 2026 
#Tutorial 6


from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input as preprocess_vgg
from tensorflow.keras.applications.resnet50 import preprocess_input as preprocess_resnet
import numpy as np
import tensorflow as tf

def load_and_preprocess_image(img_path, model_name):
  img=image.load_img(img_path,target_size=(224,224))
  img_array=image.img_to_array(img)
  img_array=np.expand_dims(img_array,axis=0)
  if model_name=='vgg16':
    return preprocess_vgg(img_array)
  elif model_name=='resnet50':
    return preprocess_resnet(img_array)

from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.resnet50 import ResNet50

vgg_model=VGG16(weights='imagenet')
resnet_model=ResNet50(weights='imagenet')

from tensorflow.keras.applications.vgg16 import decode_predictions as decode_vgg
from tensorflow.keras.applications.resnet50 import decode_predictions as decode_resnet

def make_predictions(model,img_array,model_name):
  preds=model.predict(img_array)
  if model_name=='vgg16':
    return decode_vgg(preds,top=5)[0]
  elif model_name=='resnet50':
    return decode_resnet(preds,top=5)[0]

def print_top_5_predictions(model,img_path,model_name):
  img_array=load_and_preprocess_image(img_path,model_name)
  predictions=make_predictions(model,img_array,model_name)
  # print(f"Top 5 preds for {model_name.upper()} model:")
  # for i,pred in enumerate(predictions):
    # print(f"{i+1}. {pred[1]} ({pred[2]*100:.2f}%)")
  return predictions

img_path=r"dog.jpg"

vgg_predictions=print_top_5_predictions(vgg_model,img_path,'vgg16')
print("top 5 predictions from VGG16:")
for i, pred in enumerate(vgg_predictions):
  print(f"{i+1}. {pred[1]} ({pred[2]*100:.2f}% probability")

resnet_predictions=print_top_5_predictions(resnet_model,img_path,'resnet50')
print("top 5 predictions from ResNet50:")
for i, pred in enumerate(resnet_predictions):
  print(f"{i+1}. {pred[1]} ({pred[2]*100:.2f}% probability")

#